// Package attest signs opsforge's supply-chain artifacts (the SBOM and the
// VEX document) into a self-contained Sigstore bundle.
//
// It signs KEY-BASED by default, with a persistent local opsforge signing key
// (an ECDSA P-256 key under ~/.config/opsforge/) — no OIDC, no network, no
// Rekor entry. That is a deliberate choice: keyless signing publishes the
// signer's OIDC identity in a public, immutable transparency log and proves
// nothing about supply-chain provenance for an artifact generated by hand on a
// laptop. Key-based signing here proves integrity + attribution to a key, and
// is honestly documented as exactly that — nothing more. Keyless stays where
// it belongs, on CI-signed releases (where the identity *is* the pipeline).
package attest

import (
	"context"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	protocommon "github.com/sigstore/protobuf-specs/gen/pb-go/common/v1"
)

// localKeypair implements sigstore-go's sign.Keypair backed by a persistent
// ECDSA P-256 key. Implementing the interface ourselves (rather than using the
// ephemeral keypair) is what gives the user a STABLE public key to verify
// against across signatures.
type localKeypair struct {
	priv *ecdsa.PrivateKey
}

func (k *localKeypair) GetHashAlgorithm() protocommon.HashAlgorithm {
	return protocommon.HashAlgorithm_SHA2_256
}

func (k *localKeypair) GetSigningAlgorithm() protocommon.PublicKeyDetails {
	return protocommon.PublicKeyDetails_PKIX_ECDSA_P256_SHA_256
}

// GetHint returns a stable key hint so a verifier can match signature to key:
// the base64 of the SHA-256 of the DER public key. It must be valid UTF-8
// because the bundle's protojson encoding stores it as a string field — raw
// digest bytes would fail to marshal.
func (k *localKeypair) GetHint() []byte {
	der, _ := x509.MarshalPKIXPublicKey(k.priv.Public())
	sum := sha256.Sum256(der)
	return []byte(base64.StdEncoding.EncodeToString(sum[:]))
}

func (k *localKeypair) GetKeyAlgorithm() string { return "ECDSA" }

func (k *localKeypair) GetPublicKey() crypto.PublicKey { return k.priv.Public() }

func (k *localKeypair) GetPublicKeyPem() (string, error) {
	der, err := x509.MarshalPKIXPublicKey(k.priv.Public())
	if err != nil {
		return "", err
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der})), nil
}

// SignData signs data and returns (signature, digest), per the Keypair
// contract. The digest is SHA-256 of the data.
func (k *localKeypair) SignData(_ context.Context, data []byte) ([]byte, []byte, error) {
	digest := sha256.Sum256(data)
	sig, err := ecdsa.SignASN1(rand.Reader, k.priv, digest[:])
	if err != nil {
		return nil, nil, err
	}
	return sig, digest[:], nil
}

// KeyPaths returns the private/public key file locations under the opsforge
// config dir.
func KeyPaths() (priv, pub string, err error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", "", err
	}
	dir := filepath.Join(home, ".config", "opsforge")
	return filepath.Join(dir, "signing.key"), filepath.Join(dir, "signing.pub"), nil
}

// loadOrCreateKeypair loads the persistent opsforge signing key, generating
// (and persisting) a fresh P-256 key on first use. The public key is written
// alongside so the user can hand it to a verifier.
func loadOrCreateKeypair() (*localKeypair, error) {
	privPath, pubPath, err := KeyPaths()
	if err != nil {
		return nil, err
	}
	if data, err := os.ReadFile(privPath); err == nil {
		priv, err := parsePrivateKey(data)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", privPath, err)
		}
		return &localKeypair{priv: priv}, nil
	}
	return generateKeypair(privPath, pubPath)
}

func generateKeypair(privPath, pubPath string) (*localKeypair, error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(privPath), 0o700); err != nil {
		return nil, err
	}
	privDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return nil, err
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: privDER})
	if err := os.WriteFile(privPath, privPEM, 0o600); err != nil {
		return nil, err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(priv.Public())
	if err != nil {
		return nil, err
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	if err := os.WriteFile(pubPath, pubPEM, 0o644); err != nil {
		return nil, err
	}
	return &localKeypair{priv: priv}, nil
}

func parsePrivateKey(pemData []byte) (*ecdsa.PrivateKey, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("no PEM block in signing key")
	}
	return x509.ParseECPrivateKey(block.Bytes)
}
